spring:
  application:
    name: demo-spring-kotlin
  datasource:
      url: jdbc:h2:mem:creditdb
      username: sa
      password: sa
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
