spring:
  application:
    name: reactive-bingo
  webflux:
    base-path: /reactive-bingo
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive-bingo

retry-config:
  max-retries: 3
  min-duration: 1

http-client:
  response-timeout: 3000
  read-timeout: 3000
